# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('uservalidation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
