# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 20:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('uservalidation', '0002_auto_20170523_2019'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('userManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
