# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
