# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursename',
            name='desc',
        ),
        migrations.AddField(
            model_name='description',
            name='course',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseName'),
            preserve_default=False,
        ),
    ]
